Hw2
MelekhinMikhail/RecipeApp pull request #2
Opened 2023-01-14 19:27 UTC by MelekhinMikhail

2023-01-15 08:35 UTC, OlgaLugacheva requested changes

2023-01-15 08:35 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp/controllers/IngredientController.java
> +    @GetMapping("/add")
PostMapping

2023-01-15 08:35 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp/controllers/IngredientController.java
> +    @GetMapping("/add")
передавай Ingredient через RequestBody

2023-01-15 08:35 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp/controllers/IngredientController.java
> +        else return ingredientService.getIngredient(id).toString();
скобочки для if и else

2023-01-15 08:35 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp/controllers/IngredientController.java
> +        else return ingredientService.getIngredient(id).toString();
Возвращать должен Ingredient а не String

2023-01-15 08:35 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp/controllers/RecipeController.java
> +    @GetMapping("/add")
Те же комментарии что и  в другом конроллере

2023-01-15 08:35 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp/controllers/IngredientController.java
> +        if (ingredientService.getIngredient(id) == null) return "Такого ингредиента нет.";
если мы не нашли ингридиент - нужно бросить исключение

2023-01-16 16:32 UTC, OlgaLugacheva approved these changes

2023-01-16 16:32 UTC, OlgaLugacheva commented on src/main/java/pro/sky/recipeapp/services/RecipeServiceImpl.java
> +        return storage.getOrDefault(id, null);
так и так null вернет через get

2023-01-20 18:26 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipeapp/services/impl/RecipeServiceImpl.java
> +    public static Map<Long, Recipe> storage = new TreeMap<>();
Лучше `private`

2023-01-20 18:26 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipeapp/services/impl/RecipeServiceImpl.java
> +        return storage.getOrDefault(id, null);
Можно просто `.get(id);` и так будет null если значения нет.

2023-01-20 18:26 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipeapp/services/impl/RecipeServiceImpl.java
> +            storage.remove(id);
`remove` можно не делать, при вызове `put` у тебя и так обновится значение по ключу.

2023-01-20 18:26 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipeapp/services/impl/RecipeServiceImpl.java
> +        if (storage.containsKey(id)) {
можно сделать немного проще, не ошибка, просто на будущее.
```
var removed = storage.remove(id);
return removed != null;
```

2023-01-20 18:26 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipeapp/services/impl/RecipeServiceImpl.java
> +        storage = new TreeMap<>();
Можно и не создавать новый объект, вызвать метод `.clear()`. Тоже не ошибка в целом.

2023-01-20 18:26 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipeapp/services/impl/RecipeServiceImpl.java
> +            return null;
`null` в таком случае лучше не возвращать, а вернуть пустую коллекцию. Можно вот так 
`Collections.emptyList();`

2023-01-20 18:26 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipeapp/services/impl/RecipeServiceImpl.java
> +        List<Recipe> list = new LinkedList<>();
Если хочется вернуть новый лист, то можно в конструктор `LinkedList` передать `storage.values()`

2023-01-20 18:26 UTC, alekseykoshelev commented on src/main/java/pro/sky/recipeapp/services/impl/RecipeServiceImpl.java
> +        if (list.size() != 0) {
Все эти проверки можно убрать и в конце просто сделать `return list;`

2023-02-05 19:48 UTC, merged